package:
  name: phonopy
  version: {{ environ.get('GIT_DESCRIBE_TAG', '') | replace('v','',1) }}

source:
  git_url: https://github.com/jochym/phonopy.git
  git_branch: {{ environ.get('GIT_BRANCH','master') }}

build:
  preserve_egg_dir: True
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}
  script_env:
    - GIT_BRANCH
  script: python setup.py install
  #entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - elastic = elastic:main
    #
    # Would create an entry point called elastic that calls elastic.main()

requirements:
  build:
    - python
    - numpy
    - matplotlib
    - pyyaml
    - h5py
    - setuptools
    - setuptools_scm

  run:
    - python
    - numpy
    - matplotlib
    - pyyaml
    - h5py

test:
  # Python imports
  imports:
    - phonopy

#  commands:
#    # You can put test commands to be run here.  Use this to test that the
#    # entry points work.
#    - cd example/MgO 
#    - phonopy -f vasprun.xml-001 vasprun.xml-002
#    - phonopy -p band.conf
#    - phonopy -p --nac band.conf

  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://atztogo.github.io/phonopy/
  license: BSD
  summary: 'Phonon calculation with finite displacements method.'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
